"""Deterministic DTO + runtime schema generation from the accepted local OpenAPI.
Requires PyYAML (the repository's existing contract validation dependency).
Run from any directory: python frontend/src/shared/api/generate_wire.py
"""
from pathlib import Path
import hashlib
import json
import yaml

ROOT = Path(__file__).resolve().parents[4]
SOURCE = ROOT / 'coord/proposals/a6-contract-v1/contracts/openapi.yaml'
EXPECTED = 'b8b5b855eb8fffd4607473a4e878a3c64820030820cabb1b0c92d70928730f97'
raw = SOURCE.read_bytes()
if hashlib.sha256(raw).hexdigest() != EXPECTED:
    raise SystemExit('Accepted contract hash differs; require consumer approval before regeneration')
schemas = yaml.safe_load(raw)['components']['schemas']

def ts(s):
    if '$ref' in s:
        return s['$ref'].split('/')[-1]
    if 'const' in s:
        return json.dumps(s['const'], ensure_ascii=False)
    if 'enum' in s:
        return ' | '.join(json.dumps(v) for v in s['enum'])
    for union in ('oneOf', 'anyOf'):
        if union in s:
            return ' | '.join(ts(v) for v in s[union])
    if s.get('type') == 'object':
        props = s.get('properties', {})
        if not props:
            return 'Record<string, unknown>' if s.get('additionalProperties') else 'Record<string, never>'
        required = s.get('required', [])
        return '{\n' + '\n'.join('  '+k+('' if k in required else '?')+': '+ts(v)+';' for k,v in props.items()) + '\n}'
    if s.get('type') == 'array':
        return 'Array<'+ts(s['items'])+'>'
    return {'string':'string', 'integer':'number', 'number':'number','boolean':'boolean','null':'null'}[s['type']]

out = Path(__file__).resolve().parent
header = '// GENERATED by generate_wire.py. Do not edit.\n// Accepted OpenAPI SHA-256: '+EXPECTED+'\n\n'
(out / 'wire.ts').write_text(header+'\n\n'.join('export type '+k+' = '+ts(v)+';' for k,v in schemas.items())+'\n')
(out / 'wire-schema.json').write_text(json.dumps(schemas, ensure_ascii=False, indent=2)+'\n')
print('Generated wire.ts and wire-schema.json from accepted '+EXPECTED)
