// GENERATED by generate_wire.py. Do not edit.
// Accepted OpenAPI SHA-256: b8b5b855eb8fffd4607473a4e878a3c64820030820cabb1b0c92d70928730f97

export type Role = "master" | "executor" | "manager" | "admin";

export type Status = "issued" | "queued" | "accepted" | "rejected" | "in_progress" | "paused" | "done" | "ai_review" | "rework" | "closed" | "cancelled";

export type Assignment = {
  executor_id: string;
  brigade_id: string | null;
};

export type Principal = {
  user_id: string;
  active: boolean;
  employee_code: string;
  role: Role;
  section_ids: Array<string>;
  on_shift: boolean;
};

export type Session = {
  principal: Principal;
  csrf_token: string;
  expires_at: string;
};

export type Login = {
  employee_code: string;
  pin: string;
};

export type FieldError = {
  path: string;
  code: string;
};

export type Problem = {
  code: "INVALID_REQUEST" | "VALIDATION_FAILED" | "UNAUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "VERSION_CONFLICT" | "TRANSITION_CONFLICT" | "OPERATION_ID_REUSED" | "INCOMPLETE_SUBMISSION" | "STALE_ASSIGNMENT" | "PHOTO_EXPIRED" | "RATE_LIMITED" | "TEMPORARILY_UNAVAILABLE" | "PAYLOAD_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE";
  message: string;
  request_id: string;
  retryable: boolean;
  current_version: number | null;
  field_errors: Array<FieldError>;
};

export type CreatePayload = {
  type: "planned" | "unplanned";
  description: string;
  section_id: string;
  equipment_id: string;
  assignment: Assignment;
  due_at: string;
  norm_minutes: number;
  priority: "normal" | "high" | "emergency";
  comment: string;
  before_photo_ids: Array<string>;
};

export type CreateOrder = {
  operation_id: string;
  expected_version: 0;
  action: "create";
  payload: CreatePayload;
};

export type MaterialUse = {
  material_id: string;
  quantity: number;
};

export type SubmitPayload = {
  work_description: string;
  work_code_id: string | null;
  materials: Array<MaterialUse>;
  after_photo_ids: Array<string>;
  comment: string;
};

export type ReviewPayload = {
  submission_id: string;
  decision: "close" | "rework";
  reason: string;
  final_score: number | null;
};

export type MissingEvidence = "WORK_CODE_REQUIRED" | "AFTER_PHOTO_REQUIRED";

export type Assessment = {
  id: string;
  submission_id: string;
  assignment_revision: number;
  schema_version: "1";
  mode: "model" | "rules_fallback" | "manual";
  model: string | null;
  model_version: string | null;
  duration_ms: number;
  recommendation: "satisfactory" | "rework_recommended" | "needs_master_review";
  score: number | null;
  reasons: Array<string>;
  evidence_ids: Array<string>;
  fallback_reason: string | null;
  stale: boolean;
  created_at: string;
};

export type Review = {
  id: string;
  submission_id: string;
  reviewer_id: string;
  decision: "close" | "rework";
  reason: string;
  final_score: number | null;
  created_at: string;
};

export type Submission = {
  id: string;
  order_id: string;
  assignment_revision: number;
  attempt_number: number;
  submitted_by: string;
  submitted_at: string;
  done_late: boolean;
  payload: SubmitPayload;
  completeness: "complete" | "incomplete";
  missing_evidence: Array<MissingEvidence>;
  assessments: Array<Assessment>;
  reviews: Array<Review>;
};

export type Order = {
  id: string;
  number: string;
  version: number;
  assignment_revision: number;
  scheduling_revision: number;
  status: Status;
  type: "planned" | "unplanned";
  description: string;
  section_id: string;
  equipment_id: string;
  assignment: Assignment;
  created_by: string;
  issued_at: string;
  due_at: string;
  norm_minutes: number;
  priority: "normal" | "high" | "emergency";
  comment: string;
  before_photo_ids: Array<string>;
  current_submission_id: string | null;
  is_overdue: boolean;
  domain_now: string;
  updated_at: string;
};

export type CommandResult = {
  order: Order;
  event_ids: Array<string>;
  submission_id: string | null;
};

export type OrderPage = {
  items: Array<Order>;
  next_cursor: string | null;
};

export type OrderEvent = {
  id: string;
  order_id: string;
  sequence: number;
  order_version: number;
  assignment_revision: number;
  scheduling_revision: number;
  reason: string | null;
  details: Record<string, unknown>;
  kind: "order.created" | "order.queued" | "order.accepted" | "order.rejected" | "order.started" | "order.paused" | "order.resumed" | "order.done" | "order.ai_review_requested" | "order.assessment_recorded" | "order.reviewed" | "order.reassigned" | "order.cancelled" | "order.priority_changed";
  actor_id: string | null;
  operation_id: string | null;
  from_status: Status | null;
  to_status: Status;
  submission_id: string | null;
  occurred_at: string;
  recorded_at: string;
};

export type EventPage = {
  items: Array<OrderEvent>;
  next_after_sequence: number;
  has_more: boolean;
};

export type StagedPhoto = {
  id: string;
  section_id: string;
  purpose: "before" | "after";
  owner_id: string;
  order_id: string | null;
  assignment_revision: number | null;
  mime_type: "image/jpeg" | "image/png" | "image/webp";
  bytes: number;
  sha256: string;
  uploaded_at: string;
  expires_at: string;
  exif_removed: boolean;
};

export type StagePhotoRequest = {
  section_id: string;
  operation_id: string;
  expected_version: 0;
  purpose: "before" | "after";
  order_id?: string;
  assignment_revision?: number;
  file: string;
};

export type QueueCommand = {
  operation_id: string;
  expected_version: number;
  action: "queue";
  payload: Record<string, never>;
};

export type AcceptCommand = {
  operation_id: string;
  expected_version: number;
  action: "accept";
  payload: Record<string, never>;
};

export type StartCommand = {
  operation_id: string;
  expected_version: number;
  action: "start";
  payload: Record<string, never>;
};

export type ResumeCommand = {
  operation_id: string;
  expected_version: number;
  action: "resume";
  payload: Record<string, never>;
};

export type RejectCommand = {
  operation_id: string;
  expected_version: number;
  action: "reject";
  payload: {
  reason: string;
};
};

export type PauseCommand = {
  operation_id: string;
  expected_version: number;
  action: "pause";
  payload: {
  reason: string;
};
};

export type SubmitCommand = {
  operation_id: string;
  expected_version: number;
  action: "submit";
  payload: SubmitPayload;
};

export type ReviewCommand = {
  operation_id: string;
  expected_version: number;
  action: "review";
  payload: ReviewPayload;
};

export type ReassignCommand = {
  operation_id: string;
  expected_version: number;
  action: "reassign";
  payload: {
  assignment: Assignment;
  reason: string;
};
};

export type CancelCommand = {
  operation_id: string;
  expected_version: number;
  action: "cancel";
  payload: {
  reason: string;
};
};

export type ChangePriorityCommand = {
  operation_id: string;
  expected_version: number;
  action: "change_priority";
  payload: {
  priority: "normal" | "high" | "emergency";
  reason: string;
};
};

export type OrderCommand = QueueCommand | AcceptCommand | StartCommand | ResumeCommand | RejectCommand | PauseCommand | SubmitCommand | ReviewCommand | ReassignCommand | CancelCommand | ChangePriorityCommand;

export type DictionaryItem = {
  id: string;
  code: string;
  label: string;
};

export type EquipmentItem = {
  id: string;
  code: string;
  label: string;
  section_id: string;
};

export type MaterialItem = {
  id: string;
  code: string;
  label: string;
  unit: string;
};

export type ExecutorItem = {
  id: string;
  employee_code: string;
  section_ids: Array<string>;
  brigade_id: string | null;
  on_shift: boolean;
  active_order_id: string | null;
  queue_count: number;
};

export type Dictionaries = {
  sections: Array<DictionaryItem>;
  equipment: Array<EquipmentItem>;
  brigades: Array<DictionaryItem>;
  executors: Array<ExecutorItem>;
  work_codes: Array<DictionaryItem>;
  materials: Array<MaterialItem>;
};

export type DeliveryJob = {
  id: string;
  order_id: string;
  assignment_revision: number;
  scheduling_revision: number;
  kind: "new_order" | "deadline_reminder" | "overdue" | "acceptance_escalation" | "manager_escalation" | "submission_ready" | "review_result";
  recipient_id: string;
  channel: string;
  bucket: string;
  due_at: string;
  state: "pending" | "sending" | "provider_accepted" | "retry" | "cancelled" | "failed";
  attempts: number;
  next_attempt_at: string;
  provider_receipt: string | null;
};
