'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const c = require('./c113_contract.cjs');
const p = require('./c113_preflight_proof.cjs');
const { privateLoginBoundary } = require('./c113_private_boundary.cjs');
function report() { return { config:{metadata:{frontend_sha:c.FRONTEND_SHA,run_id:'c113-source-test-0001'}},errors:[],stats:{expected:0,unexpected:1,skipped:0,flaky:0},suites:[{specs:[{title:p.PREFLIGHT_TITLE,tests:[{expectedStatus:'passed',status:'unexpected',results:[{status:'failed',retry:0,errors:[{message:'C113_DUMMY_FAILURE_EXPECTED'}]}]}]}]}] }; }
test('dummy proof requires exactly the intentional unexpected failure',()=>{assert.equal(p.preflightOutcome(report(),1,'c113-source-test-0001'),true); for(const mutate of [r=>{r.stats.unexpected=0;},r=>{r.stats.skipped=1;},r=>{r.suites=[];},r=>{r.suites[0].specs[0].title='C110 dummy credential failure output';},r=>{r.suites[0].specs[0].tests[0].results[0].errors=[];},r=>{r.suites[0].specs[0].tests[0].expectedStatus='failed';},r=>{r.config.metadata.frontend_sha='0'.repeat(40);}]){const r=report();mutate(r);assert.equal(p.preflightOutcome(r,1,'c113-source-test-0001'),false);} assert.equal(p.preflightOutcome(report(),0,'c113-source-test-0001'),false);});
test('private boundary suppresses all transport exception details',async()=>{await assert.rejects(privateLoginBoundary('executor',async()=>{throw Error('DUMMY_COOKIE DUMMY_DSN DUMMY_PIN DUMMY_CSRF');}),{message:'C113 BLOCKED: synthetic executor login failed; credential-bearing details suppressed'});});
test('effective runner rejects capture, inherited browser env, retries, extra reporters and config changes',()=>{const file=path.join(__dirname,'c113_playwright.config.cjs'), output='/public/report.json';const config={configFile:file,workers:1,forbidOnly:true,reporter:[['list',{printSteps:false}],['json',{outputFile:output}]]},project={retries:0,repeatEach:1,use:c.runnerUse()};c.validateEffectiveRunner(config,project,file,output);for(const mutate of [(_,pr)=>{pr.use.trace='on';},(_,pr)=>{pr.use.ignoreHTTPSErrors=true;},(_,pr)=>{pr.use.launchOptions={};},(_,pr)=>{pr.use.launchOptions.env.DALA_C113_OBSERVER_DATABASE_URL='DUMMY';},(_,pr)=>{pr.retries=1;},co=>{co.reporter.push(['html']);},co=>{co.configFile='/different';},co=>{co.workers=2;},co=>{co.forbidOnly=false;}]){const co=structuredClone(config),pr=structuredClone(project);mutate(co,pr);assert.throws(()=>c.validateEffectiveRunner(co,pr,file,output));}});
