'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const k=require('./contract.cjs'),p=require('./proof.cjs'),o=require('./observations.cjs');
const sha='a'.repeat(40),hash='b'.repeat(64),run='bcp-dummy-source-bindings';
const env={DALA_BCP_RUN_ID:run,DALA_BCP_PRODUCT_SHA:k.PRODUCT_SHA,DALA_E2E_FRONTEND_SHA:k.FRONTEND_SHA};
const hashes={'dummy.cjs':hash};
function receipt(){return {version:p.VERSION,result:'PASS',scope:'DUMMY_PRIVACY_ONLY',playwright:'1.63.0',source_sha:sha,source_files:hashes,run_id:run,product_sha:k.PRODUCT_SHA,frontend_sha:k.FRONTEND_SHA,expected_failures:1,observed_failures:1,scanned_outputs:3,sentinel_matches:0,scanned_sha256:hash,created_at:new Date().toISOString()};}
function client(){return {scope:'INSTRUMENTED_DIAGNOSTIC_ONLY',source_sha:sha,run_id:run,state:'COMPLETE',reason:'EOF_EXACT_LENGTH',comparability:'COMPARABLE',fetches:1,readers:1,reads:2,declared_bytes:5,observed_bytes:5,eof:true,sha256:hash,retained_capture_bytes:0,disposed:true};}
function evidence(){return {schema_version:1,scope:'INSTRUMENTED_DIAGNOSTIC_ONLY',c113_acceptance:'NOT_ESTABLISHED',status:'DIAGNOSTIC_COMPLETE',source_sha:sha,product_sha:k.PRODUCT_SHA,frontend_sha:k.FRONTEND_SHA,source_files:hashes,run_id:run,baseline_failed_run:'37726366034',baseline_failed_job:'113145335028',phase:'DONE',cdp:{status:'FAILED',failure:'BODY_UNAVAILABLE',bytes:null,sha256:null},client:client(),binding:{armed:true,matching_requests:1,exact_request_bound:true,invalid:false},request_before:{completion:'FAILED',failure_present:true},request_after:{completion:'FAILED',failure_present:true},ui_before:'READY',ui_after:'READY',ui_at_save:'READY',saved:{status:'VERIFIED',bytes:5,sha256:hash,cdp_exact_equality:'UNAVAILABLE',client_hash_equality:true,content_inspection:'VERIFIED',no_export_on_save:true},authority:'VERIFIED',database_unchanged:true,interpretation:'CDP_UNAVAILABLE_CLIENT_AND_SAVE_VERIFIED_INSTRUMENTED',cleanup:'OWN_CAPTURE_DISPOSED_CONTEXTS_CLOSED',timing_effect:'EXTRA_PROMISE_OBSERVERS_AND_BYTE_COPIES',raw_artifacts:'PRIVATE_DELETE_AFTER_RUN'};}
test('fresh own receipt accepts only all exact current bindings',()=>{const r=receipt();assert.equal(p.validateProof(r,sha,hashes,env),r);});
for(const [label,mutate] of [
  ['old C113 receipt',r=>r.version='c113-failure-output-v1'],['stale',r=>r.created_at=new Date(Date.now()-1800001).toISOString()],['future',r=>r.created_at=new Date(Date.now()+60000).toISOString()],
  ['source changed',r=>r.source_sha='c'.repeat(40)],['file changed',r=>r.source_files={'dummy.cjs':'c'.repeat(64)}],['wrong run',r=>r.run_id='bcp-another-run'],['wrong product',r=>r.product_sha='c'.repeat(40)],
  ['wrong frontend',r=>r.frontend_sha='c'.repeat(40)],['wrong engine',r=>r.playwright='1.62.0'],['sentinel present',r=>r.sentinel_matches=1],['unexpected success',r=>r.observed_failures=0],
])test(label+' cannot authorize a private read',()=>{const r=receipt();mutate(r);assert.throws(()=>p.validateProof(r,sha,hashes,env));});
test('no private fixture or PIN read before own receipt',()=>{const unsafe={...env,DALA_BCP_AUTHORIZED:'operator-provisioned-synthetic-only',DALA_E2E_MASTER_PIN_FILE:'/not-read/private-master',DALA_E2E_EXECUTOR_PIN_FILE:'/not-read/private-executor',DALA_E2E_FIXTURE_FILE:'/not-read/private-fixture',DALA_C113_PREFLIGHT_RECEIPT:'/old-receipt'};assert.throws(()=>k.fixture(unsafe),/FRESH_OWN_SOURCE/);assert.throws(()=>k.readPin('master',unsafe),/FRESH_OWN_SOURCE/);});
test('dummy sentinel scanner covers plain, base64, unicode-escaped and JSON',()=>{const sentinel='CANARY_secret-value';for(const value of [sentinel,Buffer.from(sentinel).toString('base64'),sentinel.split('').map(x=>'\\u'+x.charCodeAt(0).toString(16).padStart(4,'0')).join(''),JSON.stringify({message:sentinel})])assert(p.containsSentinel(value,[sentinel]));assert(!p.containsSentinel('fixed categories only',[sentinel]));});
test('reader result schema rejects private fields, invalid enums, forged completeness',()=>{assert.equal(o.validateClient(client(),sha,run).state,'COMPLETE');for(const mutate of [v=>v.nonce='PRIVATE',v=>v.reason='PRIVATE',v=>v.sha256='PRIVATE',v=>v.eof=false,v=>v.observed_bytes=4,v=>v.fetches=2,v=>v.retained_capture_bytes=5,v=>v.declared_bytes=8*1024*1024+1]){const v=client();mutate(v);assert.throws(()=>o.validateClient(v,sha,run));}});
function requests(changes={}){const frame={},page={mainFrame:()=>frame};const request={url:()=>k.EXACT_URL,method:()=> 'GET',resourceType:()=> 'fetch',frame:()=>frame,redirectedFrom:()=>null,redirectedTo:()=>null,...changes};const response={request:()=>request,url:()=>k.EXACT_URL,fromServiceWorker:()=>false};return{page,request,response};}
test('one exact original Request object required across Node observations',()=>{const {page,request,response}=requests();const b=o.originalBinding(page,'nonce');b.arm('nonce');assert(b.allow(request));b.bind(response);b.requireBound();assert.equal(b.snapshot().matching_requests,1);b.finish();assert(!b.allow(request));assert.throws(b.requireBound);});
for(const [label,change] of [['wrong URL',{url:()=>k.EXACT_URL+'&extra=1'}],['wrong method',{method:()=> 'POST'}],['wrong frame',{frame:()=>({})}],['wrong resource',{resourceType:()=> 'xhr'}],['redirect',{redirectedFrom:()=>({})}]])test(label+' fails exact request association',()=>{const {page,request}=requests(change);const b=o.originalBinding(page,'nonce');b.arm('nonce');assert(!b.allow(request));assert.equal(b.snapshot().invalid,true);});
test('response from another request or service worker is not substituted',()=>{for(const change of [{request:()=>({})},{fromServiceWorker:()=>true}]){const {page,request,response}=requests();const b=o.originalBinding(page,'nonce');b.arm('nonce');b.allow(request);assert.throws(()=>b.bind({...response,...change}));}});
test('CDP failure stays failed with independently verified client/saved result',()=>{const e=evidence();o.validateEvidence(e,receipt());assert.equal(e.cdp.status,'FAILED');assert.equal(e.saved.cdp_exact_equality,'UNAVAILABLE');assert.equal(e.c113_acceptance,'NOT_ESTABLISHED');assert(!Object.values(e).includes('PASS'));});
for(const [label,mutate] of [
  ['extra private field',e=>e.message='PRIVATE_CANARY'],['private reason',e=>e.client.reason='PRIVATE_CANARY'],['CDP fallback',e=>e.saved.cdp_exact_equality='EQUAL'],['invented C113 pass',e=>e.c113_acceptance='PASS'],
  ['saved hash mismatch',e=>e.saved.sha256='c'.repeat(64)],['inspector failure',e=>e.saved.content_inspection='PROCESS_FAILED'],['missing authority',e=>e.authority='NOT_ESTABLISHED'],['capture incomplete',e=>e.client.eof=false],
  ['extra GET',e=>e.binding.matching_requests=2],['database mutated',e=>e.database_unchanged=false],['cleanup missing',e=>e.cleanup='PENDING'],['private arbitrary enum',e=>e.phase='PRIVATE_CANARY'],
])test(label+' cannot be a complete public diagnostic',()=>{const e=evidence();mutate(e);assert.throws(()=>o.validateEvidence(e,receipt()));});
test('all agreement requires literal original-CDP byte equality',()=>{const e=evidence();e.cdp={status:'OK',failure:'NOT_OBSERVED',bytes:5,sha256:hash};e.saved.cdp_exact_equality='EQUAL';e.interpretation='THREE_OBSERVATIONS_AGREE_INSTRUMENTED';o.validateEvidence(e,receipt());e.saved.cdp_exact_equality='UNAVAILABLE';assert.throws(()=>o.validateEvidence(e,receipt()));});
test('new runtime sources are bound and originals are imported read-only',()=>{for(const name of ['browser_tap.cjs','runner.spec.cjs','runner.config.cjs','preflight.spec.cjs','preflight.config.cjs','secrecy_preflight.cjs','execute.cjs','proof.cjs','observations.cjs','contract.cjs'])assert(p.paths().includes('tests/e2e/body_capture_probe/'+name));assert(p.paths().includes('tests/e2e/c113_inspect_download.py'));assert(p.paths().includes('tests/e2e/package-lock.json'));const source=fs.readFileSync(path.join(__dirname,'runner.spec.cjs'),'utf8');assert.equal((source.match(/files\.boundedResponseBody\(response\)/g)||[]).length,1);assert(!source.includes('files.validateDownload('));});
