-- PROPOSAL ONLY. A0/human A acceptance and B0/C0 contract handshake pending.
-- PostgreSQL candidate. Not applied or syntax-tested against PostgreSQL here.
-- UUIDs generated by application; no extension privileges required.
BEGIN;
CREATE TABLE sections (id uuid PRIMARY KEY, code text UNIQUE NOT NULL, label text NOT NULL);
CREATE TABLE brigades (
  id uuid PRIMARY KEY, section_id uuid NOT NULL REFERENCES sections(id),
  code text UNIQUE NOT NULL, label text NOT NULL, UNIQUE (id, section_id)
);
CREATE TABLE employees (
  id uuid PRIMARY KEY, employee_code text UNIQUE NOT NULL,
  role text NOT NULL CHECK (role IN ('master','executor','manager','admin')),
  active boolean NOT NULL DEFAULT true, on_shift boolean NOT NULL DEFAULT false,
  brigade_id uuid REFERENCES brigades(id), pin_hash text NOT NULL
);
CREATE TABLE employee_sections (
  employee_id uuid REFERENCES employees(id), section_id uuid REFERENCES sections(id),
  PRIMARY KEY (employee_id, section_id)
);
CREATE TABLE auth_sessions (
  id uuid PRIMARY KEY, employee_id uuid NOT NULL REFERENCES employees(id),
  token_hash text UNIQUE NOT NULL, csrf_token text NOT NULL,
  created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL,
  revoked_at timestamptz, CHECK (expires_at > created_at)
);
CREATE TABLE equipment (
  id uuid PRIMARY KEY, section_id uuid NOT NULL REFERENCES sections(id),
  code text UNIQUE NOT NULL, label text NOT NULL, UNIQUE (id, section_id)
);
CREATE TABLE work_codes (id uuid PRIMARY KEY, code text UNIQUE NOT NULL, label text NOT NULL);
CREATE TABLE materials (
  id uuid PRIMARY KEY, code text UNIQUE NOT NULL, label text NOT NULL, unit text NOT NULL
);
CREATE TABLE orders (
  id uuid PRIMARY KEY, number bigint GENERATED ALWAYS AS IDENTITY UNIQUE,
  version bigint NOT NULL CHECK (version > 0),
  assignment_revision integer NOT NULL CHECK (assignment_revision > 0),
  scheduling_revision integer NOT NULL CHECK (scheduling_revision > 0),
  status text NOT NULL CHECK (status IN ('issued','queued','accepted','rejected','in_progress','paused','done','ai_review','rework','closed','cancelled')),
  type text NOT NULL CHECK (type IN ('planned','unplanned')),
  description text NOT NULL CHECK (length(btrim(description)) BETWEEN 1 AND 2000),
  section_id uuid NOT NULL REFERENCES sections(id), equipment_id uuid NOT NULL,
  executor_id uuid NOT NULL REFERENCES employees(id), brigade_id uuid,
  created_by uuid NOT NULL REFERENCES employees(id),
  issued_at timestamptz NOT NULL, due_at timestamptz NOT NULL,
  norm_minutes integer NOT NULL CHECK (norm_minutes BETWEEN 1 AND 525600),
  priority text NOT NULL CHECK (priority IN ('normal','high','emergency')),
  comment text NOT NULL DEFAULT '', current_submission_id uuid,
  updated_at timestamptz NOT NULL, UNIQUE (id, section_id),
  FOREIGN KEY (equipment_id, section_id) REFERENCES equipment(id, section_id),
  FOREIGN KEY (brigade_id, section_id) REFERENCES brigades(id, section_id)
);
-- Employee-section rights are checked live by the service. They are not an order
-- FK: revoking a scope must remain possible without deleting historical orders.
CREATE INDEX orders_executor_state_idx ON orders(executor_id,status,due_at);
CREATE INDEX orders_section_state_idx ON orders(section_id,status,due_at);
CREATE TABLE submissions (
  id uuid PRIMARY KEY, order_id uuid NOT NULL REFERENCES orders(id),
  assignment_revision integer NOT NULL CHECK (assignment_revision > 0),
  attempt_number integer NOT NULL CHECK (attempt_number > 0),
  submitted_by uuid NOT NULL REFERENCES employees(id), submitted_at timestamptz NOT NULL,
  done_late boolean NOT NULL, work_description text NOT NULL CHECK (length(btrim(work_description)) BETWEEN 1 AND 6000),
  work_code_id uuid REFERENCES work_codes(id), comment text NOT NULL DEFAULT '',
  completeness text NOT NULL CHECK (completeness IN ('complete','incomplete')),
  missing_evidence jsonb NOT NULL CHECK (jsonb_typeof(missing_evidence)='array'),
  UNIQUE (order_id, assignment_revision, attempt_number),
  UNIQUE (id, order_id, assignment_revision),
  CHECK ((completeness='complete' AND missing_evidence='[]'::jsonb) OR
         (completeness='incomplete' AND jsonb_array_length(missing_evidence)>0))
);
ALTER TABLE orders ADD CONSTRAINT orders_current_submission_fk
  FOREIGN KEY (current_submission_id, id, assignment_revision)
  REFERENCES submissions(id, order_id, assignment_revision) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE photos (
  id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES employees(id),
  section_id uuid NOT NULL REFERENCES sections(id),
  purpose text NOT NULL CHECK (purpose IN ('before','after')),
  order_id uuid REFERENCES orders(id), assignment_revision integer,
  submission_id uuid, storage_key text UNIQUE NOT NULL,
  mime_type text NOT NULL CHECK (mime_type IN ('image/jpeg','image/png','image/webp')),
  bytes bigint NOT NULL CHECK (bytes BETWEEN 1 AND 8388608),
  sha256 text NOT NULL CHECK (sha256 ~ '^[a-f0-9]{64}$'),
  uploaded_at timestamptz NOT NULL, expires_at timestamptz NOT NULL,
  attached_at timestamptz, exif_removed boolean NOT NULL CHECK (exif_removed),
  FOREIGN KEY (order_id, section_id) REFERENCES orders(id, section_id),
  FOREIGN KEY (submission_id, order_id, assignment_revision)
    REFERENCES submissions(id, order_id, assignment_revision),
  CHECK (expires_at > uploaded_at),
  CHECK ((purpose='before' AND submission_id IS NULL AND assignment_revision IS NULL) OR
         (purpose='after' AND order_id IS NOT NULL AND assignment_revision > 0)),
  CHECK (attached_at IS NULL OR order_id IS NOT NULL),
  CHECK (purpose<>'after' OR attached_at IS NULL OR submission_id IS NOT NULL)
);
CREATE INDEX photos_unattached_expiry_idx ON photos(expires_at) WHERE attached_at IS NULL;
CREATE TABLE material_writeoffs (
  submission_id uuid REFERENCES submissions(id), material_id uuid REFERENCES materials(id),
  quantity numeric(15,3) NOT NULL CHECK (quantity > 0),
  PRIMARY KEY (submission_id, material_id)
);
CREATE TABLE ai_assessments (
  id uuid PRIMARY KEY, submission_id uuid NOT NULL REFERENCES submissions(id),
  assignment_revision integer NOT NULL CHECK (assignment_revision > 0),
  mode text NOT NULL CHECK (mode IN ('model','rules_fallback','manual')),
  schema_version text NOT NULL CHECK (schema_version='1'),
  model text, model_version text, duration_ms integer NOT NULL CHECK (duration_ms >= 0),
  recommendation text NOT NULL CHECK (recommendation IN ('satisfactory','rework_recommended','needs_master_review')),
  score integer CHECK (score BETWEEN 0 AND 100),
  reasons jsonb NOT NULL CHECK (jsonb_typeof(reasons)='array'),
  evidence_ids jsonb NOT NULL CHECK (jsonb_typeof(evidence_ids)='array'),
  fallback_reason text, stale boolean NOT NULL, created_at timestamptz NOT NULL
);
CREATE TABLE reviews (
  id uuid PRIMARY KEY, submission_id uuid NOT NULL REFERENCES submissions(id),
  reviewer_id uuid NOT NULL REFERENCES employees(id),
  decision text NOT NULL CHECK (decision IN ('close','rework')),
  reason text NOT NULL CHECK (length(btrim(reason)) BETWEEN 1 AND 2000),
  final_score integer CHECK (final_score BETWEEN 0 AND 100), created_at timestamptz NOT NULL,
  UNIQUE (submission_id)
);
CREATE TABLE order_events (
  id uuid PRIMARY KEY, order_id uuid NOT NULL REFERENCES orders(id),
  sequence bigint NOT NULL CHECK (sequence > 0),
  order_version bigint NOT NULL CHECK (order_version > 0),
  assignment_revision integer NOT NULL, scheduling_revision integer NOT NULL,
  kind text NOT NULL, reason text, details jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(details)='object'),
  actor_id uuid REFERENCES employees(id), operation_id uuid,
  from_status text, to_status text NOT NULL, submission_id uuid REFERENCES submissions(id),
  occurred_at timestamptz NOT NULL, recorded_at timestamptz NOT NULL,
  UNIQUE (order_id, sequence)
);
CREATE TABLE operation_receipts (
  actor_id uuid REFERENCES employees(id), operation_id uuid,
  canonical_hash text NOT NULL CHECK (canonical_hash ~ '^[a-f0-9]{64}$'),
  resource_kind text NOT NULL CHECK (resource_kind IN ('order','photo')),
  resource_id uuid, response_status integer, response_body jsonb,
  created_at timestamptz NOT NULL, committed_at timestamptz,
  PRIMARY KEY (actor_id, operation_id),
  CHECK (response_status IS NULL OR response_status IN (200,201))
);
-- Reserve unique actor+operation_id first, then finalize within SAME transaction.
-- Deferred commit guard prevents an accidentally committed empty reservation.
CREATE FUNCTION require_complete_receipt() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM operation_receipts r
             WHERE r.actor_id=NEW.actor_id AND r.operation_id=NEW.operation_id
             AND (r.resource_id IS NULL OR r.response_status IS NULL OR
                  r.response_body IS NULL OR r.committed_at IS NULL)) THEN
    RAISE EXCEPTION 'Operation receipt must be finalized before commit';
  END IF;
  RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER receipt_complete_at_commit
  AFTER INSERT OR UPDATE ON operation_receipts DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION require_complete_receipt();
CREATE TABLE ai_jobs (
  id uuid PRIMARY KEY, submission_id uuid NOT NULL UNIQUE REFERENCES submissions(id),
  assignment_revision integer NOT NULL, state text NOT NULL CHECK (state IN ('pending','running','done','retry','failed')),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  next_attempt_at timestamptz NOT NULL, lease_until timestamptz, last_error_code text,
  created_at timestamptz NOT NULL
);
CREATE TABLE delivery_jobs (
  id uuid PRIMARY KEY, order_id uuid NOT NULL REFERENCES orders(id),
  assignment_revision integer NOT NULL, scheduling_revision integer NOT NULL,
  kind text NOT NULL CHECK (kind IN ('new_order','deadline_reminder','overdue','acceptance_escalation','manager_escalation','submission_ready','review_result')),
  recipient_id uuid NOT NULL REFERENCES employees(id), channel text NOT NULL,
  bucket text NOT NULL, due_at timestamptz NOT NULL,
  state text NOT NULL CHECK (state IN ('pending','sending','provider_accepted','retry','cancelled','failed')),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0), next_attempt_at timestamptz NOT NULL,
  lease_until timestamptz, sent_at timestamptz, provider_receipt text, last_error_code text,
  UNIQUE (order_id,assignment_revision,scheduling_revision,kind,recipient_id,channel,bucket)
);
CREATE INDEX delivery_jobs_due_idx ON delivery_jobs(state,due_at,next_attempt_at);
-- Service role must not own these tables and must not disable triggers. Migrations
-- run under a separate owner. Attachments are mutable only until initial binding.
CREATE FUNCTION deny_audit_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Audit rows are append-only'; END $$;
CREATE TRIGGER order_events_immutable BEFORE UPDATE OR DELETE ON order_events
  FOR EACH ROW EXECUTE FUNCTION deny_audit_change();
CREATE TRIGGER submissions_immutable BEFORE UPDATE OR DELETE ON submissions
  FOR EACH ROW EXECUTE FUNCTION deny_audit_change();
CREATE TRIGGER assessments_immutable BEFORE UPDATE OR DELETE ON ai_assessments
  FOR EACH ROW EXECUTE FUNCTION deny_audit_change();
CREATE TRIGGER reviews_immutable BEFORE UPDATE OR DELETE ON reviews
  FOR EACH ROW EXECUTE FUNCTION deny_audit_change();
CREATE TRIGGER material_writeoffs_immutable BEFORE UPDATE OR DELETE ON material_writeoffs
  FOR EACH ROW EXECUTE FUNCTION deny_audit_change();
COMMIT;
